on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - 'develop'
      - 'main'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "${GITHUB_REF#refs/*/}"
          if [ "${GITHUB_REF#refs/*/}" == "develop" ]; then
            echo "true"
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "false"
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # tag_name: ${{ github.ref }}
          # release_name: Release ${{ github.ref }}
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            To download execute the following statement:
            pip install git+https://github.com/TrisNol/python-sample-package@${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}